version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://bankuser:bankpassword@db:5432/bankdb
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpassword
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
